services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: disha24
    
  app:
    image: traineeapp
    container_name: springboot-app
    depends_on:
      - db
    ports:
      - "8088:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employeedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: disha24